# Instagram Post Recommendation Technique

In [68]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from  sklearn.feature_extraction import text
from sklearn.metrics.pairwise import cosine_similarity

In [104]:
instagram_data = pd.read_csv("instagram_reach.csv", index_col=0, encoding='latin1')
instagram_data.head()

,S.No,USERNAME,Caption,Followers,Hashtags,Time since posted,Likes
0,1,mikequindazzi,Who are #DataScientist and what do they do? >>...,1600,#MachineLearning #AI #DataAnalytics #DataScien...,11 hours,139
1,2,drgorillapaints,We all know where itâs going. We just have t...,880,Â #deckÂ .#macÂ #macintosh#sayhelloÂ #appleÂ #...,2 hours,23
2,3,aitrading_official,Alexander Barinov: 4 years as CFO in multinati...,255,#whoiswhoÂ #aitradingÂ #aiÂ #aitradingteam#ins...,2 hours,25
3,4,opensourcedworkplace,sfad,340,#iotÂ #cre#workplaceÂ #CDOÂ #bigdataÂ #technol...,3 hours,49
4,5,crea.vision,Ever missed a call while your phone was chargi...,304,#instamachinelearningÂ #instabigdata#instamark...,3 hours,30

In [105]:
instagram_data.shape

(100, 7)

In [40]:
# select two columns to analyse 
selected_data = instagram_data[["Caption","Hashtags"]]
selected_data.head()

,Caption,Hashtags
0,Who are #DataScientist and what do they do? >>...,#MachineLearning #AI #DataAnalytics #DataScien...
1,We all know where itâs going. We just have t...,Â #deckÂ .#macÂ #macintosh#sayhelloÂ #appleÂ #...
2,Alexander Barinov: 4 years as CFO in multinati...,#whoiswhoÂ #aitradingÂ #aiÂ #aitradingteam#ins...
3,sfad,#iotÂ #cre#workplaceÂ #CDOÂ #bigdataÂ #technol...
4,Ever missed a call while your phone was chargi...,#instamachinelearningÂ #instabigdata#instamark...

In [41]:
# we use cosine similarity to identify the similarities between captions
selected_data = selected_data.dropna(subset=["Caption"])
captions = selected_data["Caption"].tolist()
uni_tfidf = text.TfidfVectorizer(input = "content", stop_words="english")
uni_matrix = uni_tfidf.fit_transform(captions)
uni_sim = cosine_similarity(uni_matrix)

def recommend_post(x):
  return ", ".join(selected_data["Caption"].iloc[x.argsort()[-5:-1]])

selected_data["Recommended Post"] = [recommend_post(x) for x in uni_sim]
selected_data.head()

,Caption,Hashtags,Recommended Post
0,Who are #DataScientist and what do they do? >>...,#MachineLearning #AI #DataAnalytics #DataScien...,"4K Ai, 1 in 3Â #SmartphonesÂ will ship w/Â #Ma..."
1,We all know where itâs going. We just have t...,Â #deckÂ .#macÂ #macintosh#sayhelloÂ #appleÂ #...,Having a great week atÂ @ldntechweekÂ explorin...
2,Alexander Barinov: 4 years as CFO in multinati...,#whoiswhoÂ #aitradingÂ #aiÂ #aitradingteam#ins...,"Lead with theÂ #AIÂ advantage., 1 in 3Â #Smart..."
3,sfad,#iotÂ #cre#workplaceÂ #CDOÂ #bigdataÂ #technol...,"#Repost @wesabio Sometimes the truth hurts |, ..."
4,Ever missed a call while your phone was chargi...,#instamachinelearningÂ #instabigdata#instamark...,The IT industry is rapidly booming. Is your ca...

### Most Recommended Captions in Instagram

In [52]:
print("recommended posts regardless of thier captions, \n", 
      selected_data["Recommended Post"])

recommended posts regardless of thier captions,
 0     4K Ai, 1 in 3Â #SmartphonesÂ will ship w/Â #Ma...
1     Having a great week atÂ @ldntechweekÂ explorin...
2     Lead with theÂ #AIÂ advantage., 1 in 3Â #Smart...
3     #Repost @wesabio Sometimes the truth hurts |, ...
4     The IT industry is rapidly booming. Is your ca...
                            ...
8     Very impressed by the ingenuity of our PhD stu...
9     #WorldCupÂ is here and BlocSide is bringing ba...
10    Last week was pretty busy, so I had no chance ...
11    Today weâre hosting Career Services and Acad...
12    #Repost @wesabio Sometimes the truth hurts |, ...
Name: Recommended Post, Length: 94, dtype: object

In [56]:
# Cosine similarity 
selected_data = selected_data.dropna(subset=["Hashtags"])
captions = selected_data["Hashtags"].tolist()
uni_tfidf = text.TfidfVectorizer(input = "content", stop_words="english")
uni_matrix = uni_tfidf.fit_transform(captions)
uni_sim = cosine_similarity(uni_matrix)

def recommend_post(x):
  return ", ".join(selected_data["Hashtags"].iloc[x.argsort()[-5:-1]])

selected_data["Recommended Post"] = [recommend_post(x) for x in uni_sim]
selected_data.head()

,Caption,Hashtags,Recommended Post
0,Who are #DataScientist and what do they do? >>...,#MachineLearning #AI #DataAnalytics #DataScien...,#AI #machinelearning #artificialintelligence ...
1,We all know where itâs going. We just have t...,Â #deckÂ .#macÂ #macintosh#sayhelloÂ #appleÂ #...,#digitalartÂ #artedigitalÂ #parisÂ #technology...
2,Alexander Barinov: 4 years as CFO in multinati...,#whoiswhoÂ #aitradingÂ #aiÂ #aitradingteam#ins...,#machinelearningÂ #artificialintelligence#bloc...
3,sfad,#iotÂ #cre#workplaceÂ #CDOÂ #bigdataÂ #technol...,#whoiswhoÂ #aitradingÂ #aiÂ #aitradingteam#ins...
4,Ever missed a call while your phone was chargi...,#instamachinelearningÂ #instabigdata#instamark...,Â #datascienceÂ #dataÂ #techÂ #technology#futu...

### Most Recommended Hashtags in Instagram

In [65]:
recommended_post = selected_data[["Recommended Post"]]
recommended_post.reset_index(drop=True, inplace=True)
recommended_post.index += 1
recommended_post.head()

                                    Recommended Post
1   #AI #machinelearning #artificialintelligence ...
2  #digitalartÂ #artedigitalÂ #parisÂ #technology...
3  #machinelearningÂ #artificialintelligence#bloc...
4  #whoiswhoÂ #aitradingÂ #aiÂ #aitradingteam#ins...
5  Â #datascienceÂ #dataÂ #techÂ #technology#futu...

In [73]:
instagram_data.head()

,S.No,USERNAME,Caption,Followers,Hashtags,Time since posted,Likes
0,1,mikequindazzi,Who are #DataScientist and what do they do? >>...,1600,#MachineLearning #AI #DataAnalytics #DataScien...,11 hours,139
1,2,drgorillapaints,We all know where itâs going. We just have t...,880,Â #deckÂ .#macÂ #macintosh#sayhelloÂ #appleÂ #...,2 hours,23
2,3,aitrading_official,Alexander Barinov: 4 years as CFO in multinati...,255,#whoiswhoÂ #aitradingÂ #aiÂ #aitradingteam#ins...,2 hours,25
3,4,opensourcedworkplace,sfad,340,#iotÂ #cre#workplaceÂ #CDOÂ #bigdataÂ #technol...,3 hours,49
4,5,crea.vision,Ever missed a call while your phone was chargi...,304,#instamachinelearningÂ #instabigdata#instamark...,3 hours,30

In [95]:
hashtag_likes = instagram_data[["Hashtags", "Likes"]]
hashtag_likes.reset_index(drop=True, inplace=True) 
hashtag_likes.index += 1
hashtag_likes.head()

                                            Hashtags  Likes
1  #MachineLearning #AI #DataAnalytics #DataScien...    139
2  Â #deckÂ .#macÂ #macintosh#sayhelloÂ #appleÂ #...     23
3  #whoiswhoÂ #aitradingÂ #aiÂ #aitradingteam#ins...     25
4  #iotÂ #cre#workplaceÂ #CDOÂ #bigdataÂ #technol...     49
5  #instamachinelearningÂ #instabigdata#instamark...     30

In [96]:
hashtag_likes.size

200